### ISSUE TITLE
execution issue

### ISSUE THREAD

**Issue by debanjansen48** [avimanyu786/TrajectoryMergeAssist#2]
I downloaded it from 
https://github.com/avimanyu786/TrajectoryMergeAssist/releases/download/v2.1/tma_v2.1-setup.sh 

after installation call it from working folder by issuing command "tma"
working folder contain out.cms file and  trajectories

but encountered by following error

Merging both trajectories into one and generating -out.cms...
-------------------------------------------------------------
Traceback (most recent call last):
  File "/home/debanjan/Desmond/internal/bin/trj_merge.py", line 120, in <module>
    main()
  File "/home/debanjan/Desmond/internal/bin/trj_merge.py", line 93, in main
    tr = traj.read_traj(f)
  File "/home/debanjan/Desmond/internal/lib/python3.6/site-packages/schrodinger/application/desmond/packages/traj.py", line 589, in read_traj
    fmt = get_fmt(inp, format)
  File "/home/debanjan/Desmond/internal/lib/python3.6/site-packages/schrodinger/application/desmond/packages/traj.py", line 89, in get_fmt
    raise ValueError("Unrecognized trajectory format: %s" % extname)
ValueError: Unrecognized trajectory format: -mrj
mv: cannot stat 'NewMergedTrajectory.cms': No such file or directory
Error! New Merged Trajectory not created! Please contact author.

**Comment by avimanyu786** [comment]
Hello @debanjansen48,

Sorry about the delayed response. For some odd reason, I did not receive the notification. You seem to be using the Python 2 version of TMA. Please use the `tma-py3` command instead of `tma`. Python 2 is no longer supported since January 1 2020.

The trajectory directories' names that you are providing seem to be ending with `-mrj` while it expects `_trj`. The `ValueError` is therefore being reported by the backend Desmond script as an unrecognised trajectory format.

**Comment by AbelJ06-06** [comment]
I also had a similar issue 

Traceback (most recent call last):
  File "/opt/schrodinger2022-1/internal/bin/trj_merge.py", line 120, in <module>
    main()
  File "/opt/schrodinger2022-1/internal/bin/trj_merge.py", line 93, in main
    tr = traj.read_traj(f)
  File "/opt/schrodinger2022-1/internal/lib/python3.8/site-packages/schrodinger/application/desmond/packages/traj.py", line 701, in read_traj
    source = DtrSource(molfile.dtr.read(inp), name=inp)
RuntimeError: open_file_read failed
mv: cannot stat 'NewMergedTrajectory.cms': No such file or directory
Error! New Merged Trajectory not created! Please contact author.
